# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20161004_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.FileField(default='None', upload_to='profiles'),
        ),
    ]
