# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20161005_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', verbose_name='URL'),
        ),
    ]
