# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(default='', verbose_name='URL'),
        ),
    ]
